### Naive Bayes Text Classification

In [1]:
import numpy as np
import csv
import math
import random
import pandas as pd
import numpy as np
from IPython.display import display, clear_output

In [2]:
# # Generate text data for two classes, "statement" and "question"

# text_train = [['This is my novel book', 'statement'],
#               ['this book has more than one author', 'statement'],
#               ['is this my book', 'question'],
#               ['They are novels', 'statement'],
#               ['have you read this book', 'question'],
#               ['who is the novels author', 'question'],
#               ['what are the characters', 'question'],
#               ['This is how I bought the book', 'statement'],
#               ['I like fictional characters', 'statement'],
#               ['what is your favorite book', 'question']]

# text_test = [['this is the book', 'statement'], 
#              ['who are the novels characters', 'question'], 
#              ['is this the author', 'question']]

In [3]:
df = pd.read_csv('Musical_instruments_reviews.csv')
df.tail()

reviewerID        asin             reviewerName helpful  \
10256  A14B2YH83ZXMPP  B00JBIVXGC          Lonnie M. Adams  [0, 0]   
10257   A1RPTVW5VEOSI  B00JBIVXGC       Michael J. Edelman  [0, 0]   
10258   AWCJ12KBO5VII  B00JBIVXGC         Michael L. Knapp  [0, 0]   
10259  A2Z7S8B5U4PAKJ  B00JBIVXGC  Rick Langdon "Scriptor"  [0, 0]   
10260  A2WA8TDCTGUADI  B00JBIVXGC          TheTerrorBeyond  [0, 0]   

                                              reviewText  overall  \
10256            Great, just as expected.  Thank to all.      5.0   
10257  I've been thinking about trying the Nanoweb st...      5.0   
10258  I have tried coated strings in the past ( incl...      4.0   
10259  Well, MADE by Elixir and DEVELOPED with Taylor...      4.0   
10260  These strings are really quite good, but I wou...      4.0   

                                                 summary  unixReviewTime  \
10256                                         Five Stars      1405814400   
10257  Long life, and for some players, a good econom...      1404259200   
10258                                   Good for coated.      1405987200   
10259                                        Taylor Made      1404172800   
10260  These strings are really quite good, but I wou...      1405468800   

        reviewTime  
10256  07 20, 2014  
10257   07 2, 2014  
10258  07 22, 2014  
10259   07 1, 2014  
10260  07 16, 2014

### Extract X and y

In [4]:
df["Text"] = df['reviewText'].fillna('')
df = df[df['Text'] != ' ']
df['Text'] = df['Text'].str.replace('[^a-zA-Z0-9 \n\.]|\.', '')
df['Text'] = df['Text'].str.lower()
df = df[['Text', 'overall']]

In [5]:
print(df.head())

                                                Text  overall
0  not much to write about here but it does exact...      5.0
1  the product does exactly as it should and is q...      5.0
2  the primary job of this device is to block the...      5.0
3  nice windscreen protects my mxl mic and preven...      5.0
4  this pop filter is great it looks and performs...      5.0


### Split data

In [6]:
# # Load training and test data into pandas data frames
# training_data = pd.DataFrame(text_train, columns= ['sentence', 'class'])
# print(training_data['sentence'])
# testing_data = pd.DataFrame(text_test, columns= ['sentence', 'class'])
# # print(testing_data)
# print(testing_data['sentence'])

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df["Text"],df["overall"],test_size = 0.3)

# double check the shapes
assert X_train.shape[0] == y_train.shape[0]
# assert len(X_train)  == len(y_train)
assert X_test.shape[0] == y_test.shape[0]
# assert len(X_test) == len(y_test)

print('shapes of X_train, y_train')
print(X_train.shape,y_train.shape)
print('shapes of X_test, y_test')
print(X_test.shape,y_test.shape)
print(X_train)

shapes of X_train, y_train
(7182,) (7182,)
shapes of X_test, y_test
(3079,) (3079,)
7365    looks nice hardware is good and it works great...
4318    the good thing about the cable station is you ...
8483    its been a while since last we got together th...
3456    i got a pair of these strings in early august ...
9537    the action was a little high for my taste  the...
                              ...                        
4815    this mixer is just what ive been looking for t...
974     i play 5string bass both electric and acoustic...
6808    our teenager really likes these  as a beginner...
56      pretty crappy cable it works and gets the job ...
6843    how much can you say about a patch cable this ...
Name: Text, Length: 7182, dtype: object


### Training data

In [22]:
# from sklearn.feature_extraction.text import CountVectorizer
# vectorizer = CountVectorizer()
# X = vectorizer.fit_transform(training_data['sentence'])
# print("Feature names: ", vectorizer.get_feature_names())
# print("number of words: ",len(vectorizer.get_feature_names()))
# print("type: ",type(X))
# print(X.toarray())


##########WHAT FOR?############
# vectorizer2 = CountVectorizer(analyzer = 'word',ngram_range = (2,2))
# X2 = vectorizer2.fit_transform(training_data['sentence'])
# print("Feature names: ", vectorizer2.get_feature_names())
# print(type(X2))
# print(X2.toarray())

### Testing data

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
#.fit_transofrm only for training data
X_train = vectorizer.fit_transform(X_train)
# X_train = X_train.toarray()

# and transform for xtest
#.tranform only testing data (gives a sparse matrix)
X_test = vectorizer.transform(X_test)
X_test = X_test.toarray()
# print("X_test",X_test[1,:10])
# print(X_train.shape)
# print(X_test.shape)

# y_train = training_data['class']
# y_test = testing_data['class']

print("="*30,"X_train and X_test shape")
print(X_train.shape)
print(X_test.shape)

print("="*30,"y_train and y_test shape")
print(y_train.shape)
print(y_test.shape)
print(X_test[1:10])

============================== X_train and X_test shape
(7182, 25995)
(3079, 25995)
============================== y_train and y_test shape
(7182,)
(3079,)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Calculating likelihood and prior

In [10]:
def likelihood(X_class,laplace = 1):
#     print(X_class.sum(axis = 0)+laplace)
#     print(np.sum(X_class.sum(axis=0)+laplace))
    return((X_class.sum(axis = 0)+laplace))/(np.sum(X_class.sum(axis=0)+laplace)) 

In [11]:
def prior(X_class,m):
    return X_class.shape[0]/m

In [29]:
def fit(X_train,y_train):
    m,n = X_train.shape
    classes = np.unique(y_train)
    k = len(classes)

    priors = np.zeros(k) #prior for each class
    likelihoods = np.zeros((k,n))
    for idx,label in enumerate(classes):
        X_train_c = X_train[y_train == label]
        priors[idx] = prior(X_train_c,m)
#         print('priors',priors)
        likelihoods[idx,:] = likelihood(X_train_c)
    return priors,likelihoods

In [30]:
def predict(X_test,priors,likelihoods,classes):
    return np.log(priors) + X_test@ np.log( likelihoods.T )

In [35]:
priors, likelihoods = fit(X_train,y_train)
print(likelihoods)

priors [0.02074631 0.         0.         0.         0.        ]
priors [0.02074631 0.02339181 0.         0.         0.        ]
priors [0.02074631 0.02339181 0.07421331 0.         0.        ]
priors [0.02074631 0.02339181 0.07421331 0.20551378 0.        ]
priors [0.02074631 0.02339181 0.07421331 0.20551378 0.67613478]
[[2.49041191e-05 2.49041191e-05 2.49041191e-05 ... 2.49041191e-05
  2.49041191e-05 2.49041191e-05]
 [4.55612001e-05 2.27806000e-05 2.27806000e-05 ... 2.27806000e-05
  2.27806000e-05 2.27806000e-05]
 [1.25368269e-05 1.25368269e-05 1.25368269e-05 ... 1.25368269e-05
  1.25368269e-05 1.25368269e-05]
 [1.19692391e-05 1.19692391e-05 5.98461953e-06 ... 5.98461953e-06
  1.79538586e-05 1.19692391e-05]
 [7.33419225e-06 2.44473075e-06 4.88946150e-06 ... 4.88946150e-06
  2.44473075e-06 2.44473075e-06]]


In [37]:
classes = np.unique(y_test)
print("Classes: ",classes)
print("X_test shape:",X_test.shape)
print("priors shape: ",priors.shape)
print("likelihoods shape: ", likelihoods.shape)
print(likelihoods)
print("X_test@np.log(likelihoods.T) shape: ",(X_test@np.log( likelihoods.T )).shape)
yhat = predict(X_test,priors,likelihoods,classes)
print(yhat)

Classes:  [1. 2. 3. 4. 5.]
X_test shape: (3079, 25995)
priors shape:  (5,)
likelihoods shape:  (5, 25995)
[[2.49041191e-05 2.49041191e-05 2.49041191e-05 ... 2.49041191e-05
  2.49041191e-05 2.49041191e-05]
 [4.55612001e-05 2.27806000e-05 2.27806000e-05 ... 2.27806000e-05
  2.27806000e-05 2.27806000e-05]
 [1.25368269e-05 1.25368269e-05 1.25368269e-05 ... 1.25368269e-05
  1.25368269e-05 1.25368269e-05]
 [1.19692391e-05 1.19692391e-05 5.98461953e-06 ... 5.98461953e-06
  1.79538586e-05 1.19692391e-05]
 [7.33419225e-06 2.44473075e-06 4.88946150e-06 ... 4.88946150e-06
  2.44473075e-06 2.44473075e-06]]
X_test@np.log(likelihoods.T) shape:  (3079, 5)
[[ -260.32645767  -255.64851024  -242.72970303  -231.09770859
   -226.20456315]
 [ -493.53608085  -487.3713727   -453.21975111  -440.52477064
   -444.25373287]
 [ -731.31594135  -703.90819556  -650.58962633  -639.13858177
   -626.46538533]
 ...
 [ -151.05578477  -144.44068093  -140.75622776  -136.31426962
   -130.40330411]
 [ -259.31401102  -255.142

In [33]:
print("First two yhat samples: ", yhat[:2])
print(yhat.shape)
yhat = np.argmax(yhat,axis=1)
print("yhat shape after argmax: ",yhat.shape)
print("First two yhat sample: ",yhat[:500])


First two yhat samples:  [[-260.32645767 -255.64851024 -242.72970303 -231.09770859 -226.20456315]
 [-493.53608085 -487.3713727  -453.21975111 -440.52477064 -444.25373287]]
(3079, 5)
yhat shape after argmax:  (3079,)
First two yhat sample:  [4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 3 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 3 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 3 4 3 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4

In [34]:
print("Accuracy: ",np.sum(yhat==y_test)/len(y_test))

Accuracy:  0.19291977914907438
